# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallTombstone',
            fields=[
                ('stall_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
