# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0002_stalltombstone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='last_updated',
            new_name='date_updated',
        ),
        migrations.AddField(
            model_name='stall',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stalltombstone',
            name='stall_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
